### PR TITLE
copy over pose-pipelines as an example

### PR DESCRIPTION
**Pull request by J22Melody**

### CODE REVIEW

**Comment by AmitMY** [comment]
Do you intend to keep maintaining https://github.com/J22Melody/pose-pipelines ?

If so, how about just adding this in the examples directory as a git submodule? such that it would be up to date and managed separately?

**Comment by J22Melody** [comment]
Not sure at the moment, if so more functions (not pose-related) might diverge there, that's why I am not adding a submodule (= the current code here severs as a minimal example).

But I am Okay with submodule if you prefer it.

**Comment by AmitMY** [comment]
Yeah if the other repo stays - maybe a submodule for a specific commit (so it is "stuck in the past" but is still pointing to the right place)

**Comment by J22Melody** [comment]
Updated. Let's add it as a submodule, and if needed in the future, add a specific commit.

**Pull request merged**
